# Generated by Django 5.1.6 on 2025-03-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='percent_change',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
