# Generated by Django 5.1.6 on 2025-03-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_stock_percent_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.IntegerField(default=50),
        ),
    ]
