# Generated by Django 5.1.6 on 2025-03-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
