# Generated by Django 5.1.6 on 2025-03-25 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_portfolio_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='quantity',
        ),
    ]
