# Generated by Django 5.1.6 on 2025-03-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_userportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfolio',
            name='buy_price',
            field=models.FloatField(default=0.0),
        ),
    ]
