# Generated by Django 5.1.6 on 2025-03-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_userportfolio_buy_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliostock',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='portfoliostock',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='tradingbotlog',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioStock',
        ),
        migrations.DeleteModel(
            name='TradingBotLog',
        ),
    ]
