# Generated by Django 5.1.6 on 2025-03-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_setMpin',
            field=models.BooleanField(default=False),
        ),
    ]
