# Generated by Django 5.1.6 on 2025-03-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_userprofile_is_setmpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hashed_mpin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
