# Generated by Django 5.1.6 on 2025-04-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_scheduledtrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtrade',
            name='buy_price',
            field=models.FloatField(default=0),
        ),
    ]
