# Generated by Django 5.1.6 on 2025-04-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0019_alter_trade_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtrade',
            name='action',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('FAILED', 'Failed')], max_length=8),
        ),
    ]
