# Generated by Django 5.1.6 on 2025-04-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0020_alter_scheduledtrade_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtrade',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scheduledtrade',
            name='action',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=8),
        ),
    ]
